class AppImages {
  // Icons
  static const String icon1 = 'assets/icons/1.png';
  static const String icon2 = 'assets/icons/2.png';
  static const String icon3 = 'assets/icons/3.png';
  static const String icon4 = 'assets/icons/4.png';
  static const String icon5 = 'assets/icons/5.png';
  static const String icon6 = 'assets/icons/6.png';
  static const String icon7 = 'assets/icons/7.png';
  static const String icon8 = 'assets/icons/8.png';
  static const String icon9 = 'assets/icons/9.png';
  static const String icon10 = 'assets/icons/10.png';
  static const String icon11 = 'assets/icons/11.png';
  static const String icon12 = 'assets/icons/12.png';
  static const String icon13 = 'assets/icons/13.png';
  static const String icon14 = 'assets/icons/14.png';
  static const String icon15 = 'assets/icons/15.png';
  static const String icon16 = 'assets/icons/16.png';
  static const String icon17 = 'assets/icons/17.png';
  static const String icon18 = 'assets/icons/18.png';
  static const String icon19 = 'assets/icons/19.png';
  static const String icon20 = 'assets/icons/20.png';
  static const String icon21 = 'assets/icons/21.png';
  static const String icon22 = 'assets/icons/22.png';
  static const String icon23 = 'assets/icons/23.png';
  static const String icon24 = 'assets/icons/24.png';
  static const String icon25 = 'assets/icons/25.png';
  static const String icon26 = 'assets/icons/26.png';
  static const String icon27 = 'assets/icons/27.png';
  static const String icon28 = 'assets/icons/28.png';
  static const String icon29 = 'assets/icons/29.png';
  static const String icon30 = 'assets/icons/30.png';
  static const String icon31 = 'assets/icons/31.png';
  static const String icon32 = 'assets/icons/32.png';
  static const String icon33 = 'assets/icons/33.png';
  static const String icon34 = 'assets/icons/34.png';
  static const String icon35 = 'assets/icons/35.png';
  static const String icon36 = 'assets/icons/36.png';
  static const String icon37 = 'assets/icons/37.png';
  static const String icon38 = 'assets/icons/38.png';
  static const String icon39 = 'assets/icons/39.png';
  static const String icon40 = 'assets/icons/40.png';
  static const String icon41 = 'assets/icons/41.png';
  static const String icon42 = 'assets/icons/42.png';
  static const String icon43 = 'assets/icons/43.png';
  static const String icon44 = 'assets/icons/44.png';
  static const String icon45 = 'assets/icons/45.png';
  static const String icon46 = 'assets/icons/46.png';
  static const String icon47 = 'assets/icons/47.png';
  static const String icon48 = 'assets/icons/48.png';
  static const String icon49 = 'assets/icons/49.png'; // Copy icon
  static const String icon50 = 'assets/icons/50.png'; // Upload icon
  static const String icon51 = 'assets/icons/51.png'; // المبلغ icon
  static const String icon52 = 'assets/icons/52.png'; // الخصم icon
  static const String icon53 = 'assets/icons/53.png'; // المبلغ الاجمالي icon
  static const String icon54 = 'assets/icons/54.png'; // Favorite icon
  static const String icon55 = 'assets/icons/55.png'; // PDF icon
  static const String icon56 = 'assets/icons/56.png'; // Avatar 1 (1st place)
  static const String icon57 = 'assets/icons/57.png'; // Avatar 2 (2nd place)
  static const String icon58 = 'assets/icons/58.png'; // Avatar 3 (3rd place)
  static const String icon59 = 'assets/icons/59.png';
  static const String icon60 = 'assets/icons/60.png'; // Delete account icon
  static const String icon61 = 'assets/icons/61.png'; // Logout icon
  static const String icon62 = 'assets/icons/62.png';
  static const String icon63 = 'assets/icons/63.png';
  static const String icon64 = 'assets/icons/64.png';
  static const String icon65 = 'assets/icons/65.png';
  static const String icon66 = 'assets/icons/66.png';
  static const String icon67 = 'assets/icons/67.png';
  static const String icon68 = 'assets/icons/68.png';
  static const String icon69 = 'assets/icons/69.png';
  static const String icon70 = 'assets/icons/70.png'; // About page app logo
  static const String icon71 = 'assets/icons/71.png'; // WhatsApp icon
  static const String icon72 = 'assets/icons/72.png'; // Telegram icon
  static const String icon73 = 'assets/icons/73.png'; // Instagram icon
  static const String icon74 = 'assets/icons/74.png'; // Facebook icon
  static const String icon75 = 'assets/icons/75.png'; // YouTube icon
  static const String icon76 = 'assets/icons/76.png'; // TikTok icon
  // Images
  static const String image1 = 'assets/images/1.png';
  static const String image2 = 'assets/images/2.png';
  static const String image3 = 'assets/images/3.png';
  static const String image4 = 'assets/images/4.png';
  static const String image5 = 'assets/images/5.png';
  static const String image6 = 'assets/images/6.png';
  // Add your image paths here as needed
  // Example: static const String imageName = 'assets/images/image_name.png';
}
